-- ============================================================================
-- DAZN Sports-Streaming Data Operations & Intelligence Platform
-- Layered warehouse schema: raw -> staging -> analytics -> ops (governance)
-- Target: Postgres (Supabase). Every table's `source_type` column tells you
-- exactly what kind of data lives in it -- see docs/DATA_PROVENANCE.md.
--
-- source_type values used throughout this schema (do not invent others):
--   'historical_broadcast'  -> real, but archival (e.g. SoccerNet labels)
--   'current_delayed'       -> real, refreshes over time, NOT real-time (e.g. football-data.org free tier)
--   'real_research'         -> real, from a licensed research dataset (e.g. LIVE-APV, once obtained)
--   'synthetic_derived'     -> generated by us, standing in for proprietary telemetry we do not have
-- ============================================================================

create schema if not exists raw;
create schema if not exists staging;
create schema if not exists analytics;
create schema if not exists ops;

-- ----------------------------------------------------------------------------
-- OPS: provenance, refresh, validation, incidents -- the trust backbone.
-- These four tables exist before a single row of "real" data does, on purpose:
-- nothing gets analyzed until it can be traced, refreshed, checked, and
-- escalated. This is what section 7 ("where did this number come from?")
-- and section 10 (data quality as a first-class system) actually mean.
-- ----------------------------------------------------------------------------

create table ops.source_feed_registry (
    feed_id             text primary key,          -- e.g. 'soccernet_labels_v2'
    display_name        text not null,
    provider            text not null,              -- 'SoccerNet (GroupLens-style research consortium)', 'football-data.org', etc.
    source_type         text not null check (source_type in
                            ('historical_broadcast','current_delayed','real_research','synthetic_derived')),
    access_method       text not null,              -- 'pip package, zero registration', 'free API token', 'Google Form + emailed password', 'generated locally'
    license_notes        text,
    acquired_at          timestamptz,
    refresh_frequency    text,                       -- 'static (archival)', 'on-demand poll', 'n/a'
    last_refreshed_at    timestamptz,
    validation_status    text default 'not_yet_validated'
                             check (validation_status in ('not_yet_validated','passing','warning','blocked')),
    notes                text
);

create table ops.refresh_run (
    run_id          bigint generated always as identity primary key,
    feed_id         text not null references ops.source_feed_registry(feed_id),
    started_at      timestamptz not null default now(),
    finished_at     timestamptz,
    rows_ingested   integer,
    status          text check (status in ('running','succeeded','failed')),
    error_message   text
);

create table ops.validation_check (
    check_id            bigint generated always as identity primary key,
    run_id              bigint references ops.refresh_run(run_id),
    check_name          text not null,               -- e.g. 'no_duplicate_action_events'
    dataset             text not null,               -- schema.table this check ran against
    field               text,
    status              text not null check (status in ('PASS','WARNING','CRITICAL')),
    expected            text,
    actual              text,
    detected_at         timestamptz not null default now(),
    impact              text,                         -- which downstream metric/report this affects
    recommended_action  text
);

create table ops.incident (
    incident_id         bigint generated always as identity primary key,
    source               text not null,               -- feed_id or subsystem
    dataset              text,
    detected_at          timestamptz not null default now(),
    category             text not null check (category in
                             ('DATA_ISSUE','REPORTING_ISSUE','SOURCE_ISSUE','PIPELINE_ISSUE','BUSINESS_ANOMALY')),
    issue                text not null,
    severity             text not null check (severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
    affected_records     integer,
    affected_metric      text,
    likely_cause         text,
    recommended_owner    text,                          -- 'Data Engineering', 'Analytics', 'Content Ops'
    status                text not null default 'OPEN' check (status in ('OPEN','INVESTIGATING','RESOLVED')),
    resolved_at           timestamptz
);

create table ops.metric_definition (
    metric_key       text primary key,             -- 'action_event_rate_per_match'
    display_name     text not null,
    definition_sql   text not null,                 -- the governed SQL every surface (Power BI/Looker/agent) must reuse
    owner            text not null default 'Analytics',
    description      text not null,
    updated_at       timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- RAW: landing zone, as close to source-shape as practical.
-- Nothing here is cleaned, deduplicated, or typed strictly -- that's staging's job.
-- ----------------------------------------------------------------------------

create table raw.soccernet_action_events (
    raw_id           bigint generated always as identity primary key,
    game_id          text not null,                  -- SoccerNet's own match folder id, e.g. "2015-02-21 - 18-00 Chelsea 1 - 1 Burnley"
    competition      text,
    season           text,
    half             smallint,
    game_time_raw    text,                            -- SoccerNet's "MM:SS" string, kept raw on purpose
    action_class     text,                            -- one of the 17 SoccerNet action-spotting classes
    team             text,
    visibility        text,                           -- SoccerNet's 'visible'/'not shown' flag
    loaded_at         timestamptz not null default now(),
    source_file       text                              -- which Labels-v2.json this row came from
);

create table raw.football_data_fixtures (
    raw_id            bigint generated always as identity primary key,
    api_match_id      bigint not null,
    competition_code  text,
    season            text,
    utc_date_raw      text,
    status            text,
    home_team         text,
    away_team         text,
    home_score        integer,
    away_score        integer,
    fetched_at        timestamptz not null default now(),
    raw_payload       jsonb
);

create table raw.qoe_observations (
    raw_id          bigint generated always as identity primary key,
    content_ref      text,
    observation_ts   timestamptz,
    metric_name      text,                             -- 'mos_score','startup_delay_ms','rebuffer_ratio', etc.
    metric_value     numeric,
    source_type      text not null check (source_type in ('real_research','synthetic_derived')),
    generation_method text,                             -- required and non-null when source_type = 'synthetic_derived'
    loaded_at        timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- STAGING: typed, deduplicated, one row per real-world entity.
-- ----------------------------------------------------------------------------

create table staging.match (
    match_id          text primary key,               -- stable hash of game_id
    competition        text,
    season             text,
    home_team          text,
    away_team          text,
    match_date         date,
    source_type        text not null check (source_type in ('historical_broadcast','current_delayed')),
    feed_id            text not null references ops.source_feed_registry(feed_id)
);

create table staging.action_event (
    action_event_id   bigint generated always as identity primary key,
    match_id          text not null references staging.match(match_id),
    half              smallint not null check (half in (1,2)),
    game_time_seconds integer not null check (game_time_seconds >= 0),
    action_class      text not null,
    team              text,
    is_replayed       boolean not null default false,
    feed_id           text not null references ops.source_feed_registry(feed_id),
    unique (match_id, half, game_time_seconds, action_class, team)
);

create table staging.qoe_observation (
    qoe_id            bigint generated always as identity primary key,
    content_ref       text not null,
    observed_at       timestamptz not null,
    metric_name       text not null,
    metric_value      numeric not null,
    source_type       text not null check (source_type in ('real_research','synthetic_derived')),
    feed_id           text not null references ops.source_feed_registry(feed_id)
);
